apiVersion: skaffold/v2beta20
kind: Config
build:
  local:
    useDockerCLI: true
profiles:
  - name: res
    build:
      artifacts: []
    deploy:
      helm:
        releases:
          - name: gp
            chartPath: deployment/gp-stack
            overrides:
              gp:
                enabled: false
              kafka:
                advertisedListeners: "INTERNAL://$(MY_POD_NAME).gp-kafka-headless.default.svc.cluster.local:9093,CLIENT://localhost:9092"
            imageStrategy:
              helm: {}