yugabyte:
  enabled: true
  enableLoadBalancer: false
  Image:
    tag: 2.13.1.0-b112
  storage:
    ephemeral: true
  resource:
    master:
      requests:
        cpu: 0.5
        memory: 0.5Gi
    tserver:
      requests:
        cpu: 0.5
        memory: 0.5Gi
  replicas:
    master: 1
    tserver: 1

gp:
  enabled: true