gp:
  enabled: true

yugabyte:
  enabled: true
  enableLoadBalancer: false
  Image:
    tag: 2.13.1.0-b112
  storage:
    ephemeral: true
#  authCredentials:
#    ysql:
#      user: "gp_admin"
#      password: "admin"
#      database: "gp_main"
  resource:
    master:
      requests:
        cpu: 0.5
        memory: 0.5Gi
    tserver:
      requests:
        cpu: 0.5
        memory: 0.5Gi
  replicas:
    master: 1
    tserver: 1
  gflags:
    tserver:
      ysql_num_shards_per_tserver: 4

kafka:
  enabled: false
  persistence:
    enabled: false
  zookeeper:
    enabled: true
    persistence:
      enabled: false